const products = [
    {
        id: 1,
        name: 'Maçã',
        imageUrl: 'https://example.com/apple.jpg',
        price: 1.20,
        listPrice: 1.50,
        isWeighable: true,
    },
    {
        id: 2,
        name: 'Banana',
        imageUrl: 'https://example.com/banana.jpg',
        price: 0.80,
        listPrice: 1.00,
        isWeighable: true,
    },
    {
        id: 3,
        name: 'Leite',
        imageUrl: 'https://example.com/milk.jpg',
        price: 2.50,
        listPrice: 3.00,
        isWeighable: false,
    },
    {
        id: 4,
        name: 'Arroz',
        imageUrl: 'https://example.com/rice.jpg',
        price: 1.70,
        listPrice: 2.00,
        isWeighable: true,
    },
    {
        id: 5,
        name: 'Pão',
        imageUrl: 'https://example.com/bread.jpg',
        price: 1.00,
        listPrice: 1.20,
        isWeighable: false,
    },
    {
        id: 6,
        name: 'Café',
        imageUrl: 'https://example.com/coffee.jpg',
        price: 3.50,
        listPrice: 4.00,
        isWeighable: false,
    },
    {
        id: 7,
        name: 'Carne',
        imageUrl: 'https://example.com/meat.jpg',
        price: 5.00,
        listPrice: 6.00,
        isWeighable: true,
    },
    {
        id: 8,
        name: 'Frango',
        imageUrl: 'https://example.com/chicken.jpg',
        price: 4.50,
        listPrice: 5.00,
        isWeighable: true,
    },
    {
        id: 9,
        name: 'Ovos',
        imageUrl: 'https://example.com/eggs.jpg',
        price: 2.20,
        listPrice: 2.50,
        isWeighable: false,
    },
    {
        id: 10,
        name: 'Azeite',
        imageUrl: 'https://example.com/olive-oil.jpg',
        price: 6.00,
        listPrice: 7.00,
        isWeighable: false,
    },
];
